import type * as monaco from 'monaco-editor'

const NordTheme: monaco.editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    {
      foreground: '#6272a4',
      token: 'comment',
      fontStyle: 'italic',
    },
    {
      foreground: '#bd93f9',
      token: 'string',
    },
    {
      foreground: '#bd93f9',
      token: 'constant.numeric',
    },
    {
      foreground: '#bd93f9',
      token: 'constant.language',
    },
    {
      foreground: '#bd93f9',
      token: 'constant.character',
    },
    {
      foreground: '#bd93f9',
      token: 'constant.other',
    },
    {
      foreground: '#ffb86c',
      token: 'variable.other.readwrite.instance',
    },
    {
      foreground: '#ff79c6',
      token: 'constant.character.escaped',
    },
    {
      foreground: '#ff79c6',
      token: 'constant.character.escape',
    },
    {
      foreground: '#ff79c6',
      token: 'string source',
    },
    {
      foreground: '#ff79c6',
      token: 'string source.ruby',
    },
    {
      foreground: '#ff5555',
      token: 'source.ruby string.regexp.classic.ruby',
    },
    {
      foreground: '#ff5555',
      token: 'source.ruby string.regexp.mod-r.ruby',
    },
    {
      foreground: '#ff79c6',
      token: 'keyword',
    },
    {
      foreground: '#ff79c6',
      token: 'storage',
    },
    {
      foreground: '#8be9fd',
      fontStyle: 'italic',
      token: 'storage.type',
    },
    {
      foreground: '#8be9fd',
      fontStyle: 'italic',
      token: 'storage.type.namespace',
    },
    {
      foreground: '#ff79c6',
      fontStyle: 'italic',
      token: 'storage.type.class',
    },
    {
      foreground: '#8be9fd',
      fontStyle: 'underline',
      token: 'entity.name.class',
    },
    {
      foreground: '#66d9ef',
      fontStyle: 'underline',
      token: 'meta.path',
    },
    {
      foreground: '#8be9fd',
      fontStyle: 'italic underline',
      token: 'entity.other.inherited-class',
    },
    {
      foreground: '#50fa7b',
      token: 'entity.name.function',
    },
    {
      foreground: '#ffb86c',
      fontStyle: 'italic',
      token: 'variable.parameter',
    },
    {
      foreground: '#ff79c6',
      token: 'entity.name.tag',
    },
    {
      foreground: '#50fa7b',
      token: 'entity.other.attribute-name',
    },
    {
      foreground: '#8be9fd',
      token: 'support.function',
    },
    {
      foreground: '#6be5fd',
      token: 'support.constant',
    },
    {
      foreground: '#66d9ef',
      fontStyle: 'italic',
      token: 'support.type',
    },
    {
      foreground: '#66d9ef',
      fontStyle: 'italic',
      token: 'support.class',
    },
    {
      foreground: '#66d9ef',
      fontStyle: 'italic',
      token: 'support.other.namespace',
    },
    {
      foreground: '#f8f8f0',
      background: 'ff79c6',
      token: 'invalid',
    },
    {
      foreground: '#f8f8f0',
      background: 'bd93f9',
      token: 'invalid.deprecated',
    },
    {
      foreground: '#cfcfc2',
      token: 'meta.structure.dictionary.json string.quoted.double.json',
    },
    {
      foreground: '#6272a4',
      token: 'meta.diff',
    },
    {
      foreground: '#6272a4',
      token: 'meta.diff.header',
    },
    {
      foreground: '#ff79c6',
      token: 'markup.deleted',
    },
    {
      foreground: '#50fa7b',
      token: 'markup.inserted',
    },
    {
      foreground: '#e6db74',
      token: 'markup.changed',
    },
    {
      foreground: '#bd93f9',
      token: 'constant.numeric.line-number.find-in-files - match',
    },
    {
      foreground: '#e6db74',
      token: 'entity.name.filename',
    },
    {
      foreground: '#f83333',
      token: 'message.error',
    },
    {
      foreground: '#eeeeee',
      token:
        'punctuation.definition.string.begin.json - meta.structure.dictionary.value.json',
    },
    {
      foreground: '#eeeeee',
      token:
        'punctuation.definition.string.end.json - meta.structure.dictionary.value.json',
    },
    {
      foreground: '#8be9fd',
      token: 'meta.structure.dictionary.json string.quoted.double.json',
    },
    {
      foreground: '#f1fa8c',
      token: 'meta.structure.dictionary.value.json string.quoted.double.json',
    },
    {
      foreground: '#50fa7b',
      token:
        'meta meta meta meta meta meta meta.structure.dictionary.value string',
    },
    {
      foreground: '#ffb86c',
      token: 'meta meta meta meta meta meta.structure.dictionary.value string',
    },
    {
      foreground: '#ff79c6',
      token: 'meta meta meta meta meta.structure.dictionary.value string',
    },
    {
      foreground: '#bd93f9',
      token: 'meta meta meta meta.structure.dictionary.value string',
    },
    {
      foreground: '#50fa7b',
      token: 'meta meta meta.structure.dictionary.value string',
    },
    {
      foreground: '#ffb86c',
      token: 'meta meta.structure.dictionary.value string',
    },
    {
      foreground: '#ffb86c',
      fontStyle: 'italic',
      token: 'markup.strike',
    },
    {
      foreground: '#ffb86c',
      fontStyle: 'bold',
      token: 'markup.bold',
    },
    {
      foreground: '#ffb86c',
      fontStyle: 'italic',
      token: 'markup.italic',
    },
    {
      foreground: '#8be9fd',
      token: 'markup.heading',
    },
    {
      foreground: '#ff79c6',
      token: 'punctuation.definition.list_item.markdown',
    },
    {
      foreground: '#6272a4',
      fontStyle: 'italic',
      token: 'markup.quote',
    },
    {
      foreground: '#6272a4',
      background: '6272a4',
      fontStyle: 'italic',
      token: 'punctuation.definition.blockquote.markdown',
    },
    {
      foreground: '#6272a4',
      token: 'meta.separator',
    },
    {
      foreground: '#50fa7b',
      token: 'text.html.markdown markup.raw.inline',
    },
    {
      foreground: '#bd93f9',
      fontStyle: 'underline',
      token: 'markup.underline',
    },
    {
      foreground: '#cfcfc2',
      token: 'markup.raw.block',
    },
    {
      foreground: '#f8f8f2',
      token: 'markup.raw.block.fenced.markdown source',
    },
    {
      foreground: '#6272a4',
      fontStyle: 'italic',
      token: 'punctuation.definition.fenced.markdown',
    },
    {
      foreground: '#6272a4',
      fontStyle: 'italic',
      token: 'variable.language.fenced.markdown',
    },
    {
      foreground: '#6272a4',
      fontStyle: 'italic',
      token: 'variable.language.fenced.markdown',
    },
    {
      foreground: '#ff79c6',
      token: 'punctuation.accessor',
    },
    {
      foreground: '#ff79c6',
      token: 'meta.function.return-type',
    },
    {
      foreground: '#ffffff',
      token: 'punctuation.section.block.begin',
    },
    {
      foreground: '#ffffff',
      token: 'punctuation.section.block.end',
    },
    {
      foreground: '#ff79c6',
      token: 'punctuation.section.embedded.begin',
    },
    {
      foreground: '#ff79c6',
      token: 'punctuation.section.embedded.end',
    },
    {
      foreground: '#ff79c6',
      token: 'punctuation.separator.namespace',
    },
    {
      foreground: '#50fa7b',
      token: 'variable.function',
    },
    {
      foreground: '#ffffff',
      token: 'variable.other',
    },
    {
      foreground: '#bd93f9',
      token: 'variable.language',
    },
    {
      foreground: '#8be9fd',
      token: 'entity.name.module.ruby',
    },
    {
      foreground: '#bd93f9',
      token: 'entity.name.constant.ruby',
    },
    {
      foreground: '#ffffff',
      token: 'support.function.builtin.ruby',
    },
    {
      foreground: '#ff79c6',
      token: 'storage.type.namespace.cs',
    },
    {
      foreground: '#8be9fd',
      token: 'entity.name.namespace.cs',
    },
  ],

  colors: {
    'terminal.background': '#282A36',
    'terminal.foreground': '#f6f6f4',
    'terminal.ansiBrightBlack': '#7b7f8b',
    'terminal.ansiBrightRed': '#f07c7c',
    'terminal.ansiBrightGreen': '#78f09a',
    'terminal.ansiBrightYellow': '#f6f6ae',
    'terminal.ansiBrightBlue': '#d6b4f7',
    'terminal.ansiBrightMagenta': '#f49dda',
    'terminal.ansiBrightCyan': '#adf6f6',
    'terminal.ansiBrightWhite': '#ffffff',
    'terminal.ansiBlack': '#262626',
    'terminal.ansiRed': '#ee6666',
    'terminal.ansiGreen': '#62e884',
    'terminal.ansiYellow': '#e7ee98',
    'terminal.ansiBlue': '#bf9eee',
    'terminal.ansiMagenta': '#f286c4',
    'terminal.ansiCyan': '#97e1f1',
    'terminal.ansiWhite': '#f6f6f4',
    contrastBorder: '#191A21',
    focusBorder: '#7b7f8b',
    foreground: '#f8f8f2',
    'selection.background': '#bf9eee',
    errorForeground: '#ee6666',
    'button.background': '#44475A',
    'button.foreground': '#f6f6f4',
    'dropdown.background': '#343746',
    'dropdown.border': '#191A21',
    'dropdown.foreground': '#f6f6f4',
    'input.background': '#282A36',
    'input.foreground': '#f6f6f4',
    'input.border': '#191A21',
    'input.placeholderForeground': '#7b7f8b',
    'inputOption.activeBorder': '#bf9eee',
    'inputValidation.infoBorder': '#f286c4',
    'inputValidation.warningBorder': '#FFB86C',
    'inputValidation.errorBorder': '#ee6666',
    'badge.foreground': '#f6f6f4',
    'badge.background': '#44475A',
    'progressBar.background': '#f286c4',
    'list.activeSelectionBackground': '#44475A',
    'list.activeSelectionForeground': '#f6f6f4',
    'list.dropBackground': '#44475A',
    'list.focusBackground': '#44475A75',
    'list.highlightForeground': '#97e1f1',
    'list.hoverBackground': '#44475A75',
    'list.inactiveSelectionBackground': '#44475A75',
    'list.warningForeground': '#FFB86C',
    'list.errorForeground': '#ee6666',
    'activityBar.background': '#343746',
    'activityBar.inactiveForeground': '#7b7f8b',
    'activityBar.foreground': '#f6f6f4',
    'activityBar.activeBorder': '#FF79C680',
    'activityBar.activeBackground': '#BD93F910',
    'activityBarBadge.background': '#f286c4',
    'activityBarBadge.foreground': '#f6f6f4',
    'sideBar.background': '#262626',
    'sideBarTitle.foreground': '#f6f6f4',
    'sideBarSectionHeader.background': '#282A36',
    'sideBarSectionHeader.border': '#191A21',
    'editorGroup.border': '#bf9eee',
    'editorGroup.dropBackground': '#44475A70',
    'editorGroupHeader.tabsBackground': '#191A21',
    'tab.activeBackground': '#282A36',
    'tab.activeForeground': '#f6f6f4',
    'tab.border': '#191A21',
    'tab.activeBorderTop': '#FF79C680',
    'tab.inactiveBackground': '#262626',
    'tab.inactiveForeground': '#7b7f8b',
    'editor.foreground': '#f6f6f4',
    'editor.background': '#282A36',
    'editorLineNumber.foreground': '#7b7f8b',
    'editor.selectionBackground': '#44475A',
    'editor.selectionHighlightBackground': '#424450',
    'editor.foldBackground': '#262626',
    'editor.wordHighlightBackground': '#8BE9FD50',
    'editor.wordHighlightStrongBackground': '#50FA7B50',
    'editor.findMatchBackground': '#FFB86C80',
    'editor.findMatchHighlightBackground': '#FFFFFF40',
    'editor.findRangeHighlightBackground': '#44475A75',
    'editor.hoverHighlightBackground': '#8BE9FD50',
    'editor.lineHighlightBorder': '#44475A',
    'editor.lineHighlightBackground': '#44475A',
    'editorLink.activeForeground': '#97e1f1',
    'editor.rangeHighlightBackground': '#BD93F915',
    'editor.snippetTabstopHighlightBackground': '#282A36',
    'editor.snippetTabstopHighlightBorder': '#7b7f8b',
    'editor.snippetFinalTabstopHighlightBackground': '#282A36',
    'editor.snippetFinalTabstopHighlightBorder': '#62e884',
    'editorWhitespace.foreground': '#FFFFFF1A',
    'editorIndentGuide.background': '#FFFFFF1A',
    'editorIndentGuide.activeBackground': '#FFFFFF45',
    'editorRuler.foreground': '#FFFFFF1A',
    'editorCodeLens.foreground': '#7b7f8b',
    'editorOverviewRuler.border': '#191A21',
    'editorOverviewRuler.selectionHighlightForeground': '#FFB86C',
    'editorOverviewRuler.wordHighlightForeground': '#97e1f1',
    'editorOverviewRuler.wordHighlightStrongForeground': '#62e884',
    'editorOverviewRuler.modifiedForeground': '#8BE9FD80',
    'editorOverviewRuler.addedForeground': '#50FA7B80',
    'editorOverviewRuler.deletedForeground': '#FF555580',
    'editorOverviewRuler.errorForeground': '#FF555580',
    'editorOverviewRuler.warningForeground': '#FFB86C80',
    'editorOverviewRuler.infoForeground': '#8BE9FD80',
    'editorError.foreground': '#ee6666',
    'editorWarning.foreground': '#97e1f1',
    'editorGutter.modifiedBackground': '#8BE9FD80',
    'editorGutter.addedBackground': '#50FA7B80',
    'editorGutter.deletedBackground': '#FF555580',
    'gitDecoration.modifiedResourceForeground': '#97e1f1',
    'gitDecoration.deletedResourceForeground': '#ee6666',
    'gitDecoration.untrackedResourceForeground': '#62e884',
    'gitDecoration.ignoredResourceForeground': '#7b7f8b',
    'gitDecoration.conflictingResourceForeground': '#FFB86C',
    'diffEditor.insertedTextBackground': '#50FA7B20',
    'diffEditor.removedTextBackground': '#FF555550',
    'editorWidget.background': '#262626',
    'editorSuggestWidget.background': '#262626',
    'editorSuggestWidget.foreground': '#f6f6f4',
    'editorSuggestWidget.selectedBackground': '#44475A',
    'editorHoverWidget.background': '#282A36',
    'editorHoverWidget.border': '#7b7f8b',
    'editorMarkerNavigation.background': '#262626',
    'peekView.border': '#44475A',
    'peekViewEditor.background': '#282A36',
    'peekViewEditor.matchHighlightBackground': '#F1FA8C80',
    'peekViewResult.background': '#262626',
    'peekViewResult.fileForeground': '#f6f6f4',
    'peekViewResult.lineForeground': '#f6f6f4',
    'peekViewResult.matchHighlightBackground': '#F1FA8C80',
    'peekViewResult.selectionBackground': '#44475A',
    'peekViewResult.selectionForeground': '#f6f6f4',
    'peekViewTitle.background': '#191A21',
    'peekViewTitleDescription.foreground': '#7b7f8b',
    'peekViewTitleLabel.foreground': '#f6f6f4',
    'merge.currentHeaderBackground': '#50FA7B90',
    'merge.incomingHeaderBackground': '#BD93F990',
    'editorOverviewRuler.currentContentForeground': '#62e884',
    'editorOverviewRuler.incomingContentForeground': '#bf9eee',
    'panel.background': '#282A36',
    'panel.border': '#bf9eee',
    'panelTitle.activeBorder': '#f286c4',
    'panelTitle.activeForeground': '#f6f6f4',
    'panelTitle.inactiveForeground': '#7b7f8b',
    'statusBar.background': '#191A21',
    'statusBar.foreground': '#f6f6f4',
    'statusBar.debuggingBackground': '#ee6666',
    'statusBar.debuggingForeground': '#191A21',
    'statusBar.noFolderBackground': '#191A21',
    'statusBar.noFolderForeground': '#f6f6f4',
    'statusBarItem.prominentBackground': '#ee6666',
    'statusBarItem.prominentHoverBackground': '#FFB86C',
    'statusBarItem.remoteForeground': '#f6f6f4',
    'statusBarItem.remoteBackground': '#bf9eee',
    'titleBar.activeBackground': '#262626',
    'titleBar.activeForeground': '#f6f6f4',
    'titleBar.inactiveBackground': '#191A21',
    'titleBar.inactiveForeground': '#7b7f8b',
    'notification.background': '#282A36',
    'notification.foreground': '#f6f6f4',
    'notification.buttonBackground': '#44475A',
    'notification.buttonForeground': '#f6f6f4',
    'notification.buttonHoverBackground': '#44475A75',
    'notification.errorBackground': '#ee6666',
    'notification.errorForeground': '#f6f6f4',
    'notification.infoBackground': '#97e1f1',
    'notification.infoForeground': '#282A36',
    'notification.warningBackground': '#FFB86C',
    'notification.warningForeground': '#282A36',
    'extensionButton.prominentForeground': '#f6f6f4',
    'extensionButton.prominentBackground': '#50FA7B90',
    'extensionButton.prominentHoverBackground': '#50FA7B60',
    'pickerGroup.border': '#bf9eee',
    'pickerGroup.foreground': '#97e1f1',
    'debugToolBar.background': '#262626',
    'walkThrough.embeddedEditorBackground': '#262626',
    'settings.headerForeground': '#f6f6f4',
    'settings.modifiedItemForeground': '#FFB86C',
    'settings.modifiedItemIndicator': '#FFB86C',
    'settings.dropdownBackground': '#262626',
    'settings.dropdownForeground': '#f6f6f4',
    'settings.dropdownBorder': '#191A21',
    'settings.checkboxBackground': '#262626',
    'settings.checkboxForeground': '#f6f6f4',
    'settings.checkboxBorder': '#191A21',
    'settings.textInputBackground': '#262626',
    'settings.textInputForeground': '#f6f6f4',
    'settings.textInputBorder': '#191A21',
    'settings.numberInputBackground': '#262626',
    'settings.numberInputForeground': '#f6f6f4',
    'settings.numberInputBorder': '#191A21',
    'breadcrumb.foreground': '#7b7f8b',
    'breadcrumb.background': '#282A36',
    'breadcrumb.focusForeground': '#f6f6f4',
    'breadcrumb.activeSelectionForeground': '#f6f6f4',
    'breadcrumbPicker.background': '#191A21',
    'listFilterWidget.background': '#343746',
    'listFilterWidget.outline': '#424450',
    'listFilterWidget.noMatchesOutline': '#ee6666',
  },
}

export default NordTheme
